#!/bin/sh
set -eu

PROGRAM=$(basename "$0")

TOOLCHAIN=$(dirname "$(dirname "$(realpath "$0")")")
RESOURCE_DIR=${TOOLCHAIN}/resource
SYSROOT=${TOOLCHAIN}/sysroot
TARGET=aarch64-linux-android21

CLANG="${CLANG-clang}"
CLANGXX="${CLANGXX-clang++}"

case "${PROGRAM}" in
*clang | *clang++)
	if ! test "${1+1}" || { test "${1+1}" && ! test "$1"x = "-cc1"x; }; then
		case "${PROGRAM}" in
		*-linux-android*-clang | *-linux-android*-clang++)
			TARGET=$(echo "${PROGRAM}" | grep -E -o "(aarch64|x86_64|i686|riscv64)-linux-android[1-9]+|armv7a-linux-androideabi[1-9]+")
			ABI="$(echo "${TARGET}" | grep -E -o -e '.+-.+-android(eabi)?')"
			API="$(echo "${TARGET}" | sed -E 's/.+-linux-android(eabi)?//')"

			# https://github.com/termux/termux-packages/issues/8273
			if test "${API}" -lt 29; then
				set -- "$@" -Wl,--gc-sections
			fi
			;;
		esac

		case "${PROGRAM}" in
		*clang) BIN="${CLANG}" ;;
		*clang++) BIN="${CLANGXX}" ;;
		esac

		version_info=$("${BIN}" -v 2>&1)
		if echo "${version_info}" | grep -q llvmbox; then
			## These options are necessarily for llvmbox
			sys_include_dir="${SYSROOT}/usr/include/$(echo "${TARGET}" | sed 's/armv7a/arm/' | sed -E 's/(android(eabi)?)[0-9]+/\1/')"
			set -- "$@" \
				-isystem "${SYSROOT}/usr/include/c++/v1" \
				-isystem "${SYSROOT}/usr/include" \
				-isystem "${sys_include_dir}"
		elif echo "${version_info}" | grep -q alpine; then
			set -- "$@" -B "${TOOLCHAIN}/wrappers/alpine"
		elif echo "${version_info}" | grep -q zig; then
			set -- "$@" -B "${TOOLCHAIN}/wrappers/zig"
		fi

		set -- \
			-B "${TOOLCHAIN}/bin" \
			-resource-dir "${RESOURCE_DIR}" \
			--sysroot="${SYSROOT}" \
			--target="${TARGET}" \
			"$@"
	fi
	;;
*)
	# shellcheck disable=SC2059
	printf "Usage:\n  ln -s ${PROGRAM} aarch64-linux-android24-clang\n"
	exit 1
	;;
esac

exec "${BIN}" "$@"
